#!/bin/sh
#
# auditrecv
# receiver for illumos/solaris audit_remote.so stream
#
# Copyright 2019 Alex Wilson <alex@uq.edu.au>
# The University of Queensland
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
set -ex
. /lib/svc/share/smf_include.sh

AUDIT_IP=1.2.3.4
AUDIT_PORT=1234

case "$1" in
  start)
    auditconfig -setclass AUE_SETAUDIT_ADDR as
    auditconfig -setclass AUE_SETAUDIT as
    auditconfig -setpolicy argv,cnt,zonename
    auditconfig -setflags ex,pm,as,lo
    auditconfig -setnaflags lo,as
    auditconfig -setplugin audit_remote active p_hosts=$AUDIT_IP:$AUDIT_PORT:dummy
    auditconfig -setplugin audit_remote active p_timeout=90
    auditconfig -setplugin audit_remote active p_retries=2
    auditconfig -setplugin audit_remote active qsize=32768 32768
    auditconfig -setqbufsz 1048576
    auditconfig -setqhiwater 16384
    svcadm restart auditd
    ;;
  stop)
    auditconfig -setplugin audit_remote inactive
    auditconfig -setnaflags lo
    auditconfig -setflags ex,lo
    auditconfig -setqbufsz 8192
    auditconfig -setqhiwater 100
    svcadm restart auditd
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit $SMF_EXIT_ERR_CONFIG
    ;;
esac

exit $SMF_EXIT_OK
