#!/bin/sh
#
# auditrecv
# receiver for illumos/solaris audit_remote.so stream
#
# Copyright 2019 Alex Wilson <alex@uq.edu.au>
# The University of Queensland
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

set -ex
. /lib/svc/share/smf_include.sh

case "$1" in
  start)
    rm -fr /root/gss32 /root/gss64
    cp -a /usr/lib/gss /root/gss32
    cp -a /usr/lib/amd64/gss /root/gss64
    mount -F lofs /root/gss32 /usr/lib/gss
    mount -F lofs /root/gss64 /usr/lib/amd64/gss
    cp /opt/custom/lib/gss/mech_dummy.so.1 /root/gss32/
    cp /opt/custom/lib/amd64/gss/mech_dummy.so.1 /root/gss64/
    printf "dummy\t\t\t1.3.6.1.4.1.42.2.26.1.2 mech_dummy.so.1\n" >> /etc/gss/mech
    ;;
  stop)
    umount /usr/lib/gss
    umount /usr/lib/amd64/gss
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit $SMF_EXIT_ERR_CONFIG
    ;;
esac

exit $SMF_EXIT_OK
